// export const SHOP_NAME = "Laundry G 99";
export const SHOP_NAME = "Laundry Karpet Marelan G 99";
export const SHOP_MOTTO = "Cuci Karpet Terdekat, Cepat & Bersih di Medan Marelan";
export const SHOP_DESCRIPTION = "Kami Laundry Karpet Marelan G 99 menawarkan hasil cucian bersih, cepat, dan dengan harga terjangkau dengan pelayanan ramah dan profesional. Teknologi modern kami memastikan cucian Anda bersih sempurna setiap saat.";
export const SHOP_ADDRESS = "Jl. Marelan Raya Pasar 3, Kec. Medan Marelan, Kota Medan, Sumatera Utara";
export const SHOP_PHONE = "+6281361610795";
export const SHOP_PHONE_SHOW = "+62 813-6161-0795";
export const SHOP_PHONE_2 = "+62895330398255";
export const SHOP_PHONE_SHOW_2 = "+62 895-3303-98255";
export const SHOP_EMAIL = "cakra.ds@gmail.com"; // [TO DO]
export const SHOP_IG = "#";
export const SHOP_FB = "#";
export const SHOP_TIKTOK = "#";